[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "22.12.0"
  NPM_CONFIG_PRODUCTION = "false"
  # Configure secret scanning to ignore safe NEXT_PUBLIC_* values
  SECRETS_SCAN_OMIT_KEYS = "NEXT_PUBLIC_API_URL,NEXT_PUBLIC_API_BASE_URL,NEXT_PUBLIC_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY,NEXT_PUBLIC_GOOGLE_ANALYTICS_ID,NEXT_PUBLIC_LOGROCKET_ID,NEXT_PUBLIC_SENTRY_DSN,NEXT_PUBLIC_APP_NAME,NEXT_PUBLIC_APP_DESCRIPTION,NEXT_PUBLIC_APP_VERSION,NEXT_PUBLIC_GOOGLE_CLIENT_ID,NEXT_PUBLIC_ENABLE_ANALYTICS,NEXT_PUBLIC_ENABLE_DEBUG,NEXT_PUBLIC_ENABLE_SOURCE_MAPS,NEXT_PUBLIC_ENABLE_BETA_FEATURES,NEXT_PUBLIC_ENABLE_EXPERIMENTAL_FEATURES,NEXT_PUBLIC_ENABLE_PWA,NEXT_PUBLIC_ENABLE_OFFLINE_SUPPORT,NEXT_PUBLIC_ENABLE_CACHING,NEXT_PUBLIC_MAX_FILE_SIZE,NEXT_PUBLIC_MAX_UPLOAD_CONCURRENT,NEXT_PUBLIC_SESSION_TIMEOUT,NEXT_PUBLIC_AUTH_REDIRECT_URL,NEXT_PUBLIC_LOGOUT_REDIRECT_URL,NEXT_PUBLIC_ENABLE_HOT_RELOAD,NEXT_PUBLIC_ENABLE_ERROR_BOUNDARY,NEXT_PUBLIC_ENABLE_PERFORMANCE_MONITORING,NEXT_PUBLIC_ENABLE_ACCESSIBILITY_FEATURES,NEXT_PUBLIC_SUPPORT_EMAIL,NEXT_PUBLIC_DOCS_URL,NEXT_PUBLIC_ENABLE_SOCIAL_LOGIN,NEXT_PUBLIC_ENABLE_TWO_FACTOR_AUTH,NEXT_PUBLIC_ENABLE_SSO,NEXT_PUBLIC_ENABLE_ENTERPRISE_FEATURES,NODE_ENV"
  # Optional: ignore build output paths if scanner still flags bundles
  SECRETS_SCAN_OMIT_PATHS = ".next/**,.netlify/**"

[[plugins]]
  package = "@netlify/plugin-nextjs"
